name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Workflow Status
        uses: microsoft/teams-notification@v1
        with:
          webhook-url: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URL }}
          status: ${{ job.status }}
          include-jobs: "my-job"
