name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Workflow Status
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "text": "Workflow Status: ${{ job.status }}",
            "title": "Workflow Notification",
            "themeColor": "0072C6"
          }' ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URL }}
