name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
      #Build EmployeeManagement
      #publish build and push artifact of EmployeeManagement.API
    - name: Publish EmployeeManagement.API
      run:  dotnet publish EmployeeManagement/EmployeeManagement.API/EmployeeManagement.API.csproj -c Release -o '$(Build.ArtifactStagingDirectory)/EmployeeManagement.API'
    
    - name: zip EmployeeManagement.API art
      run: |
        cd $(Build.ArtifactStagingDirectory)
        ls
      # tar -cvzf EmployeeManagement.API.tar.gz EmployeeManagement.API
        

