name: .NET build & deploy 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
      #Build EmployeeManagement
      #publish build and push artifact of EmployeeManagement.API
    - name: Publish EmployeeManagement.API
      run: |
        dotnet publish EmployeeManagement/EmployeeManagement.API/EmployeeManagement.API.csproj -c Release -o $GITHUB_WORKSPACE/EmployeeManagement.API
        cd $GITHUB_WORKSPACE 
        zip -r EmployeeManagement.API.zip cd $GITHUB_WORKSPACE/EmployeeManagement.API

      #publish build and push artifact of EmployeeManagement.Application
    - name: Publish EmployeeManagement.Application
      run: | 
        dotnet publish EmployeeManagement/EmployeeManagement.Application/EmployeeManagement.Application.csproj -c Release -o $GITHUB_WORKSPACE/EmployeeManagement.Application 
        cd $GITHUB_WORKSPACE
        zip -r EmployeeManagement.Application.zip $GITHUB_WORKSPACE/EmployeeManagement.Application
    
    - name: Upload a Build EmployeeManagement.Application Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: EmployeeManagement.Application
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/*.zip
        if-no-files-found: error
