name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      #EmployeeManagement
      #publish build and push artifact of EmployeeManagement.API
    - name: Publish EmployeeManagement.API
      run: dotnet publish EmployeeManagement/EmployeeManagement.API/EmployeeManagement.API.csproj -c Release -o EmployeeManagement.API
    
    - name: Upload a Build EmployeeManagement.API Artifact 
      uses: actions/upload-artifact@v2.3.1
      with:
        name: EmployeeManagement.API
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/EmployeeManagement.API/**
        if-no-files-found: error
      
      #publish build and push artifact of EmployeeManagement.Application
    - name: Publish EmployeeManagement.Application
      run: dotnet publish EmployeeManagement/EmployeeManagement.Application/EmployeeManagement.Application.csproj -c Release -o EmployeeManagement.Application
    
    - name: Upload a Build EmployeeManagement.Application Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: EmployeeManagement.Application
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/EmployeeManagement.Application/**
        if-no-files-found: error

      
      #publish build and push artifact of EmployeeManagement.Core
    - name: Publish EmployeeManagement.Core
      run: dotnet publish EmployeeManagement/EmployeeManagement.Core/EmployeeManagement.Core.csproj -c Release -o EmployeeManagement.Core
    
    - name: Upload a Build EmployeeManagement.Core Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: EmployeeManagement.Core
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/EmployeeManagement.Core/**
        if-no-files-found: error

      #publish build and push artifact of EmployeeManagement.DataAccess
    - name: Publish EmployeeManagement.DataAccess
      run: dotnet publish EmployeeManagement/EmployeeManagement.DataAccess/EmployeeManagement.DataAccess.csproj -c Release -o EmployeeManagement.DataAccess
    
    - name: Upload a Build EmployeeManagement.DataAccess Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: EmployeeManagement.DataAccess
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/EmployeeManagement.DataAccess/**
        if-no-files-found: error

      #RouteManagement

      #publish build and push artifact of RouteManagement.API 
      # on path use EmployeeManagement/EmployeeManagement - cause artifact store under that dir

    - name: Publish RouteManagement.API
      run: dotnet publish RouteManagement/RouteManagement.API/RouteManagement.API.csproj -c Release -o /home/runner/work/RouteManagement/RouteManagement/RouteManagement.API/
    
    - name: Upload a Build RouteManagement.API Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: RouteManagement.API
        path: /home/runner/work/RouteManagement/RouteManagement/RouteManagement.API/**
        if-no-files-found: error

      #publish build and push artifact of RouteManagement.Application 

    - name: Publish RouteManagement.Application
      run: dotnet publish RouteManagement/RouteManagement.Application/RouteManagement.Application.csproj -c Release -o RouteManagement.Application
    
    - name: Upload a Build RouteManagement.Application Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: RouteManagement.Application
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/RouteManagement.Application/**
        if-no-files-found: error

      #publish build and push artifact of RouteManagement.Core 

    - name: Publish RouteManagement.Core
      run: dotnet publish RouteManagement/RouteManagement.Core/RouteManagement.Core.csproj -c Release -o RouteManagement.Core
    
    - name: Upload a Build RouteManagement.Core Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: RouteManagement.Core
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/RouteManagement.Core/**
        if-no-files-found: error

      #publish build and push artifact of RouteManagement.DataAccess 

    - name: Publish RouteManagement.DataAccess
      run: dotnet publish RouteManagement/RouteManagement.DataAccess/RouteManagement.DataAccess.csproj -c Release -o RouteManagement.DataAccess
    
    - name: Upload a Build RouteManagement.DataAccess Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: RouteManagement.DataAccess
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/RouteManagement.DataAccess/**
        if-no-files-found: error

    #Utilities
    #publish build and push artifact of Utilities 

    - name: Publish Utilities
      run: dotnet publish Utilities/Utilities.csproj -c Release -o Utilities
    
    - name: Upload a Build Utilities Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: Utilities
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/Utilities/**
        if-no-files-found: error

    #FerryManagement
    #publish build and push artifact of FerryManagement.Web 

    - name: Publish FerryManagement.Web
      run: dotnet publish WebUI/FerryManagement.Web/FerryManagement.Web.csproj -c Release -o FerryManagement.Web
    
    - name: Upload a Build FerryManagement.Webs Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: FerryManagement.Web
        path: /home/runner/work/EmployeeManagement/EmployeeManagement/FerryManagement.Web/**
        if-no-files-found: error
